[package]
name = "chat_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = "0.8"
